In [ ]:
# Open customers.csv
import pandas as pd
df = pd.read_csv("customers.csv")
df.head()

,CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_AGE,CUSTOMER_GENDER,CITY,STATE,ANNUAL_PURCHASES,ANNUAL_VISITS,LAST_VISIT_DAYS,NUMBER_RETURNS
0,1,Joe Black,23.0,M,Westminster,CA,"$1,071",13,3,3
1,2,JOHN Michels,42.0,M,Napa,CA,"$6,442",29,46,4
2,3,Christina YANG,34.0,F,Parma,OH,"$11,588",21,104,1
3,4,Leo Wong,65.0,M,Lehi,UT,"$5,053",23,79,1
4,5,Mark Matters,32.0,M,Palm Beach Gardens,FL,"$14,425",13,94,3

In [ ]:
# Visualize all columns name
for col in df.columns:
  print(col)

CUSTOMER_ID
CUSTOMER_NAME
CUSTOMER_AGE
CUSTOMER_GENDER
CITY
STATE
ANNUAL_PURCHASES
ANNUAL_VISITS
LAST_VISIT_DAYS
NUMBER_RETURNS

In [ ]:
# Display rows with missing values
df[df.isnull().any(axis=1)]

,CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_AGE,CUSTOMER_GENDER,CITY,STATE,ANNUAL_PURCHASES,ANNUAL_VISITS,LAST_VISIT_DAYS,NUMBER_RETURNS
11,12,Lie Nielsen,NaN,M,Oceanside,CA,"$19,961",11,24,0
28,29,Christina Schoen,NaN,F,Parma,OH,"$14,921",4,61,6
35,36,Abigale Bernhard,NaN,F,Stanton,CA,"$2,291",9,96,5
54,55,Lila Schuster,34.0,NaN,Parma,OH,"$18,440",3,45,8
55,56,Sadye Moen,NaN,M,Lehi,UT,"$12,914",6,70,4
57,58,Adah Simonis,NaN,M,Aliso Viejo,CA,"$18,200",5,106,6
59,60,Abby Haley,NaN,F,Duluth,MI,"$13,791",18,109,4
72,73,Maybell McLaughlin,NaN,F,Providence,RI,"$2,488",7,106,9
81,82,Keara Hauck,NaN,F,Chicago,IL,"$4,512",21,16,5
91,92,Violet Stamm,NaN,F,Detroit,MI,"$19,973",27,71,7

In [ ]:
# Drop rows with missing values
df = df.dropna()

# Display rows with missing values
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_AGE, CUSTOMER_GENDER, CITY, STATE, ANNUAL_PURCHASES, ANNUAL_VISITS, LAST_VISIT_DAYS, NUMBER_RETURNS]
Index: []

In [ ]:
# Trim spaces in all string columns

df_obj = df.select_dtypes(['object'])
df[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())
df.head()

,CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_AGE,CUSTOMER_GENDER,CITY,STATE,ANNUAL_PURCHASES,ANNUAL_VISITS,LAST_VISIT_DAYS,NUMBER_RETURNS
0,1,Joe Black,23.0,M,Westminster,CA,"$1,071",13,3,3
1,2,JOHN Michels,42.0,M,Napa,CA,"$6,442",29,46,4
2,3,Christina YANG,34.0,F,Parma,OH,"$11,588",21,104,1
3,4,Leo Wong,65.0,M,Lehi,UT,"$5,053",23,79,1
4,5,Mark Matters,32.0,M,Palm Beach Gardens,FL,"$14,425",13,94,3

In [ ]:
# Capitalize letters in column Customer_Name
df['CUSTOMER_NAME'] = df['CUSTOMER_NAME'].str.capitalize()
df.head()

,CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_AGE,CUSTOMER_GENDER,CITY,STATE,ANNUAL_PURCHASES,ANNUAL_VISITS,LAST_VISIT_DAYS,NUMBER_RETURNS
0,1,Joe black,23.0,M,Westminster,CA,"$1,071",13,3,3
1,2,John michels,42.0,M,Napa,CA,"$6,442",29,46,4
2,3,Christina yang,34.0,F,Parma,OH,"$11,588",21,104,1
3,4,Leo wong,65.0,M,Lehi,UT,"$5,053",23,79,1
4,5,Mark matters,32.0,M,Palm Beach Gardens,FL,"$14,425",13,94,3

In [ ]:
# Convert Customer_Age from Float to Integer
df['CUSTOMER_AGE'] = df['CUSTOMER_AGE'].astype('int')
df.head()

,CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_AGE,CUSTOMER_GENDER,CITY,STATE,ANNUAL_PURCHASES,ANNUAL_VISITS,LAST_VISIT_DAYS,NUMBER_RETURNS
0,1,Joe black,23,M,Westminster,CA,"$1,071",13,3,3
1,2,John michels,42,M,Napa,CA,"$6,442",29,46,4
2,3,Christina yang,34,F,Parma,OH,"$11,588",21,104,1
3,4,Leo wong,65,M,Lehi,UT,"$5,053",23,79,1
4,5,Mark matters,32,M,Palm Beach Gardens,FL,"$14,425",13,94,3

In [15]:
# Recode CUSTOMER_GENDER with F = 0 and M = 1
df['CUSTOMER_GENDER'] = df['CUSTOMER_GENDER'].replace({'F': 0, 'M': 1})
df.head()

,CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_AGE,CUSTOMER_GENDER,CITY,STATE,ANNUAL_PURCHASES,ANNUAL_VISITS,LAST_VISIT_DAYS,NUMBER_RETURNS
0,1,Joe black,23,1,Westminster,CA,"$1,071",13,3,3
1,2,John michels,42,1,Napa,CA,"$6,442",29,46,4
2,3,Christina yang,34,0,Parma,OH,"$11,588",21,104,1
3,4,Leo wong,65,1,Lehi,UT,"$5,053",23,79,1
4,5,Mark matters,32,1,Palm Beach Gardens,FL,"$14,425",13,94,3

In [28]:
# Remove the , in annual purchases
df['ANNUAL_PURCHASES'] = df['ANNUAL_PURCHASES'].str.replace(',', '')
df['ANNUAL_PURCHASES'] = df['ANNUAL_PURCHASES'].str.replace('$', '')
df.head()

,CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_AGE,CUSTOMER_GENDER,CITY,STATE,ANNUAL_PURCHASES,ANNUAL_VISITS,LAST_VISIT_DAYS,NUMBER_RETURNS
0,1,Joe black,23,1,Westminster,CA,1071,13,3,3
1,2,John michels,42,1,Napa,CA,6442,29,46,4
2,3,Christina yang,34,0,Parma,OH,11588,21,104,1
3,4,Leo wong,65,1,Lehi,UT,5053,23,79,1
4,5,Mark matters,32,1,Palm Beach Gardens,FL,14425,13,94,3

In [29]:
# Convert ANNUAL_PURCHASES TO FLOAT

df['ANNUAL_PURCHASES'] = df['ANNUAL_PURCHASES'].astype('float')
df.head()

,CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_AGE,CUSTOMER_GENDER,CITY,STATE,ANNUAL_PURCHASES,ANNUAL_VISITS,LAST_VISIT_DAYS,NUMBER_RETURNS
0,1,Joe black,23,1,Westminster,CA,1071.0,13,3,3
1,2,John michels,42,1,Napa,CA,6442.0,29,46,4
2,3,Christina yang,34,0,Parma,OH,11588.0,21,104,1
3,4,Leo wong,65,1,Lehi,UT,5053.0,23,79,1
4,5,Mark matters,32,1,Palm Beach Gardens,FL,14425.0,13,94,3

In [31]:
# Create a new column where Adult = CUSTOMER_AGE < 65 and Senior = CUSTOMER_AGE >= 65
import numpy as np

df['CUSTOMER_TYPE'] = np.where(df['CUSTOMER_AGE']< 65, 'Adult', 'Senior')
df.head()

,CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_AGE,CUSTOMER_GENDER,CITY,STATE,ANNUAL_PURCHASES,ANNUAL_VISITS,LAST_VISIT_DAYS,NUMBER_RETURNS,CUSTOMER_TYPE
0,1,Joe black,23,1,Westminster,CA,1071.0,13,3,3,Adult
1,2,John michels,42,1,Napa,CA,6442.0,29,46,4,Adult
2,3,Christina yang,34,0,Parma,OH,11588.0,21,104,1,Adult
3,4,Leo wong,65,1,Lehi,UT,5053.0,23,79,1,Senior
4,5,Mark matters,32,1,Palm Beach Gardens,FL,14425.0,13,94,3,Adult

In [33]:
# Show all the CUSTOMER_TYPE with 'Adult'

df_filtered = df[df['CUSTOMER_TYPE'] == 'Adult']
df_filtered.head()

,CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_AGE,CUSTOMER_GENDER,CITY,STATE,ANNUAL_PURCHASES,ANNUAL_VISITS,LAST_VISIT_DAYS,NUMBER_RETURNS,CUSTOMER_TYPE
0,1,Joe black,23,1,Westminster,CA,1071.0,13,3,3,Adult
1,2,John michels,42,1,Napa,CA,6442.0,29,46,4,Adult
2,3,Christina yang,34,0,Parma,OH,11588.0,21,104,1,Adult
4,5,Mark matters,32,1,Palm Beach Gardens,FL,14425.0,13,94,3,Adult
5,6,Julio caesar,43,1,Aliso Viejo,CA,18267.0,6,93,2,Adult

In [ ]:
#Save the file as customers_clean.csv
df.to_csv('customers_clean.csv', index=False)